source_rules:
  - path: /home/ubuntu/flatiron
    include: "LICENSE|README\\.md"
    exclude: "/\\.|docker"
  - path: /home/ubuntu/flatiron/python/flatiron
    include: "\\.py$"
  - path: /home/ubuntu/flatiron/docker/config
    include: "flake8|prod.lock"
    exclude: "cache|__pypackages__"
rename_rules:
  - regex: "/home/ubuntu/flatiron"
    replace: "/home/ubuntu/build/repo"
  - regex: "/python|/docker/config|/docker"
    replace: ""
  - regex: "prod.lock"
    replace: "pdm.lock"
group_rules:
  - name: test
    regex: "(__init__|_test)\\.py$|flake8\\.ini$|resources|\\.lock$"
  - name: prod
    regex: "__init__\\.py$"
line_rules:
  - group: prod
    exclude: test
