services:
  flatiron:
    container_name: flatiron
    image: flatiron:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.dockerfile
      secrets:
        - secret-env
    ports:
      - "9100:9000"
      - "9180:8080"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
      - config/secret-env
    volumes:
      - ../:/home/ubuntu/flatiron
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
      - /mnt/storage-02:/mnt/storage
    working_dir: "/home/ubuntu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
secrets:
  secret-env:
    file: config/secret-env
